version: "3.7"

services:

  frontend:
    build:
      context: ./bee-front
    command: npm start
    volumes:
      - ./bee-front/src:/app/src
    tty: true
    stdin_open: true
    ports:
      - '3000:3000'

  api:
    build:
      context: ./bee-api
    command: uvicorn main:app --host 0.0.0.0  --port 8000
    volumes:
      - ./bee-api:/app
    environment:
      - POSTGRES_DB="${POSTGRES_DB}"
      - POSTGRES_USER="${POSTGRES_USER}"
      - POSTGRES_PASSWORD="${POSTGRES_PASSWORD}"
    ports:
      - '8000:8000'
    depends_on:
      - api_postgresql


  api_postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  nginx:
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - api

volumes:
  api_postgresql: