global:
  scrape_interval: 15s

scrape_configs:
- job_name: 'prometheus'
  scrape_interval: 15s
  metrics_path: /prometheus/metrics
  static_configs:
  - targets:
    - localhost:9090

- job_name: 'bee_app'
  scrape_interval: 5s
  metrics_path: /metrics
  static_configs:
  - targets:
    - app:8000

- job_name: 'node-exporter'
  scrape_interval: 5s
  static_configs:
  - targets:
    - node_exporter:9100
