apiVersion: apps/v1
kind: Deployment
metadata:
  name: bee-db
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bee-db
  template:
    metadata:
      labels:
        app: bee-db
      namespace: bee-app
    spec:
      containers:
      - name: bee-db
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          value: postgresql
        - name: POSTGRES_PASSWORD
          value: postgresql
        - name: POSTGRES_DB
          value: bee-database
        - name: POSTGRES_HOST
          value: localhost
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 128Mi
            cpu: 100m