apiVersion: apps/v1
kind: Deployment
metadata:
  name: bee-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bee-api
  template:
    metadata:
      labels:
        app: bee-api
      namespace: bee-app
    spec:
      containers:
      - name: bee-api
        image: bee/fastapi
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: 128Mi
            cpu: 50m
          limits:
            memory: 128Mi
            cpu: 50m
