apiVersion: apps/v1
kind: Deployment
metadata:
  name: bee-front
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bee-front
  template:
    metadata:
      labels:
        app: bee-front
      namespace: bee-app
    spec:
      containers:
      - name: bee-front
        image: bee/frontend
        ports:
        - containerPort: 3000
        resources:
            requests:
              memory: 64Mi
              cpu: 50m
            limits:
              memory: 64Mi
              cpu: 50m
